baseURL = ""
languageCode = "en-us"
title = "Mahesh Sanikommu"
theme = "resume"

[params]
    firstName = "Mahesh"
    lastName = "Sanikommu"
    address = "San Ramon, CA"
    phone = "1-785-214-3209"
    contactNote = "Dev Tools Engineer"
    profileImage = "/img/13221336_10209547928000774_7125687210749509266_o.jpg"
    email = "maheshreddy.sanikommu@ge.com"
    description = "Sr Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://linkedin.com/in/mahesh-reddy-sanikommu-44b132172"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/mahesh-sanikommu/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "key"

[params.google.analytics]
    trackerID = "XX-123446-01"
